### ISSUE TITLE
Using "verifyArbitrary" from NodeJS (backend)

### ISSUE THREAD

**Issue by mariowise** [chainapsis/keplr-wallet#1198]
I'm trying to implement a login feature with keplr wallet on a traditional client-server oriented architecture. I'm doing this by asking the user to sign a challenge string in the frontend (web application) and then I want to verify the signature in the backend to grant a session.

The web application basically does 

```
chainId = "cosmoshub-4";
await window.keplr.enable(chainId);
offlineSigner = window.keplr.getOfflineSigner(chainId);
accounts = await offlineSigner.getAccounts();
signature = await window.keplr.signArbitrary(chainId, accounts[0].address, "challenge");
```

Is there a way to leverage the `@keplr-wallet` libraries to verify the signature in the NodeJS backend. I've been trying to use `@keplr-wallet/provider` but when I try to run the `verifyArbitrary` in the backend I'm getting an error around `sendMessage` which I assume is the javascript trying to talk to the extension, which is not defined in the backend.

```
Uncaught TypeError: Cannot read properties of undefined (reading 'sendMessage')
    at /app/express/node_modules/@keplr-wallet/router/build/simple.js:55:32
    at Generator.next (<anonymous>)
    at /app/express/node_modules/@keplr-wallet/router/build/simple.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/app/express/node_modules/@keplr-wallet/router/build/simple.js:4:12)
    at sendSimpleMessage (/app/express/node_modules/@keplr-wallet/router/build/simple.js:54:12)
    at /app/express/node_modules/@keplr-wallet/provider/build/core.js:345:48
    at new Promise (<anonymous>)
```

**Comment by mariowise** [comment]
Found an answer [here](https://www.reddit.com/r/cosmosnetwork/comments/10enacr/verifying_signed_message_in_backend_nodejs/?rdt=49158&onetap_auto=true&one_tap=true). For me though, it worked without buffering the `msg`:

```
cosmos = require("@keplr-wallet/cosmos");
address = "cosmos1jnecr0...";
signature = JSON.parse('{"pub_key":{"type":"tendermint/PubKeySecp256k1","value":"A5+pm8cDd..."},"signature":"KcgXuY7sd..."}');
chainId = "cosmoshub-4";

uint8Signature = new Uint8Array(Buffer.from(signature.signature, "base64"));
uint8Pubkey = new Uint8Array(Buffer.from(signature.pub_key.value, "base64"));

res = cosmos.verifyADR36Amino(prefix, address, "challenge", uint8Pubkey, uint8Signature);
```
