### ISSUE TITLE
Governance page inaccessible for ixo chain

### ISSUE THREAD

**Issue by demondayza** [chainapsis/keplr-wallet#581]
**Describe the bug**

**To Reproduce**
1. Go to governance page https://wallet.keplr.app/chains/ixo?tab=governance
2. Click on nothing, just let the page load
3. See error Application error: a client-side exception has occurred (see the browser console for more information).

**Expected behavior**
Page expected to load without errors.

**Device details (please complete the following information):**
 - OS: Windows 11, Latest MacOS
 - Browser: Firefox 107.0.1, Chrome 108.0.5359.94 (Brave)
 - Keplr Version: 0.11.21

**Additional context**
Error from console that seems relevent:
_app-0fdcbe1cce32206c.js:23 TypeError: Cannot read properties of undefined (reading '0')
    at _ (802.9c65797eeef0d369.js:1:3123)
    at ak (framework-348fd793b828b7db.js:9:60918)
    at up (framework-348fd793b828b7db.js:9:72804)
    at i (framework-348fd793b828b7db.js:9:120373)
    at oD (framework-348fd793b828b7db.js:9:99115)
    at framework-348fd793b828b7db.js:9:98982
    at oO (framework-348fd793b828b7db.js:9:98989)
    at oE (framework-348fd793b828b7db.js:9:95741)
    at oP (framework-348fd793b828b7db.js:9:96130)
    at r8 (framework-348fd793b828b7db.js:9:44779)
    at framework-348fd793b828b7db.js:9:93633

**Comment by demondayza** [comment]
Hi Guys. 

Any feedback on this?

**Comment by dogemos** [comment]
Hey @demondayza, we've not been able to replicate this yet. Looking into it more.

**Comment by demondayza** [comment]
Hey @dogemos thank you, if theres anyway I can help by providing additional information please let me know. One comment is that the issue doesnt occur on the classic keplr.

**Comment by dogemos** [comment]
One things that could help us find a leads would be account balances. Can you provide an address of an account that you were able to reproduce the error with?

**Comment by demondayza** [comment]
Hey @dogemos the issue has been resolved as of this morning. Thank you for your investigation I can confirm that on all the platforms I tested on it is now working.
