### ISSUE TITLE
KeplrWalletConnectV1#signAmino Throws Error

### ISSUE THREAD

**Issue by RyanTimesTen** [chainapsis/keplr-wallet#701]
Hello 👋 

I've checked [the docs](https://docs.keplr.app/api/#sign-amino) and [help desk](https://keplr.crunch.help/en/search?query=signAmino) for an example of using the `signAmino` function on `KeplrWalletConnectV1`, but have been unable to find anything. Could you point me to an example for this?

I'm running a dapp, and after connecting, I'm trying to send a signature request to the wallet like this:
```ts
const res = await keplr.signAmino('osmosis-1', accountPublicAddress, {
  account_number: '0',
  chain_id: 'osmosis-1',
  fee: {
    amount: [],
    gas: '0',
  },
  memo: '',
  msgs: [
    {
      type: 'sign/MsgSignData',
      value: {
        signer: accountPublicAddress,
        data: Buffer.from(messageToSign, 'base64'),
      },
    },
  ],
  sequence: '0',
});
```

But i'm getting this error in the console:
```
Error: Unknown character b
    at http://localhost:4201/vendor.js:92993:31
    at Array.forEach (<anonymous>)
    at EventManager.trigger (http://localhost:4201/vendor.js:92991:23)
    at WalletConnect._handleIncomingMessages (http://localhost:4201/vendor.js:93770:32)
```

Would love some help using this function!

Versions:
```
"@keplr-wallet/wc-client": "^0.11.51",
"@walletconnect/client": "^1.8.0"
```

**Comment by Thunnini** [comment]
In mobile, adr36 is not supported yet and what you tried is the wrong sign doc, so of course it is normal to fail.

#664
