### ISSUE TITLE
Migration fails with `Error: Cannot read properties of null (reading 'fromRed')`

### ISSUE THREAD

**Issue by junhoyeo** [chainapsis/keplr-wallet#757]
**Describe the bug**

When I enter my password correctly at `UnlockPage` with `needMigration`(`Enter your password to upgrade.`), It shows me the `Start Migration` button. I clicked that and it fails with `Invalid password` after loading a bit.

I used `Inspect` to view the extension logs in the console and found this:

```
Error: Cannot read properties of null (reading 'fromRed')
    at t.InExtensionMessageRequester.<anonymous> (66.bundle.js:1:223493)
    at Generator.next (<anonymous>)
    at a (66.bundle.js:1:222719)
```

This is different from the "real" `Invalid password` error, which is `Error: Unmatched mac`

**Screenshots**

![image](https://github.com/chainapsis/keplr-wallet/assets/32605822/c629efc9-8152-4147-94e5-2c9717e90db9)

**Device details (please complete the following information):**
 - OS: OS X
 - Browser: Google Chrome 114.0.5735.106 (Official Build) (arm64)
 - Keplr Version: ~~0.12.8~~ 0.12.9 (Issue persists in latest version)
 - Hardware Wallet: -

**Additional context**
my wallets are tied, preventing me selling my osmo

**Comment by Thunnini** [comment]
흠... 사실 이 오류는 아마 준호님 혼자에게만 나는 오류인 것 같거든요 그래서 재현이 쉽지 않아서 해결하기가 난해해요... 혹시 이전에 1.0에서 계정을 만들때 먼가 특이한 방법으로 하셨거나 extension 내부 state를 개발자 모드로 수정했거나 한게 있나요?

**Comment by junhoyeo** [comment]
> 흠... 사실 이 오류는 아마 준호님 혼자에게만 나는 오류인 것 같거든요 그래서 재현이 쉽지 않아서 해결하기가 난해해요... 혹시 이전에 1.0에서 계정을 만들때 먼가 특이한 방법으로 하셨거나 extension 내부 state를 개발자 모드로 수정했거나 한게 있나요?

- 따로 변경한 것은 딱히 없습니다! 대신 private key로 import 한 계정이 한 50여개 추가되어 있었던 걸로 기억합니다 ㅋㅋㅋ
- 다행히 자주 쓰는 지갑 키를 찾아서 피해는 없었습니다. 👍

**Comment by junhoyeo** [comment]
closing since issue was resolved for me, maybe someone can reopen if they encounter the same error again
