### ISSUE TITLE
Claim All button failing

### ISSUE THREAD

**Issue by kombos** [chainapsis/keplr-wallet#818]
**Describe the bug**
Trying to call the claim all in the 'staked' tab to claim all rewards, is continuously failing, due to calling of simulate post method. This is when claiming the AssetMantle tokens ($MNTL). the error that is showing is : 
Failed to get a response from https://rest.assetmantle.one/cosmos/tx/v1beta1/simulate

**To Reproduce**
1. Go to 'Staked' tab
2. Have some $MNTL tokens already staked, ready to be claimed
3. click on 'Claim All' button

**Expected behavior**
Claim all operation should execute successfully

**Screenshots**
<img width="357" alt="image" src="https://github.com/chainapsis/keplr-wallet/assets/18464450/bc660409-a12e-42c7-a26d-88e86776c2fe">

**Comment by Thunnini** [comment]
When I did that, I got an error like below. I guess it's because the modified logic of that chain itself doesn't follow the standard of cosmos-sdk.

```
{
    "code": 2,
    "message": "rpc error: code = Unknown desc = recovered: startingPeriod cannot be greater than endingPeriod\nstack:\ngoroutine 83623294 [running]:\nruntime/debug.Stack()\n\truntime/debug/stack.go:24 +0x65\ngithub.com/cosmos/cosmos-sdk/baseapp.newDefaultRecoveryMiddleware.func1({0x1b3b300, 0x279fff0})\n\tgithub.com/cosmos/cosmos-sdk@v0.45.16/baseapp/recovery.go:71 +0x27\ngithub.com/cosmos/cosmos-sdk/baseapp.newRecoveryMiddleware.func1({0x1b3b300?, 0x279fff0?})\n\tgithub.com/cosmos/cosmos-sdk@v0.45.16/baseapp/recovery.go:39 +0x30\ngithub.com/cosmos/cosmos-sdk/baseapp.processRecovery({0x1b3b300, 0x279fff0}, 0xc040d918c0?)\n\tgithub.com/cosmos/cosmos-sdk@v0.45.16/baseapp/recovery.go:28 +0x37\ngithub.com/cosmos/cosmos-sdk/baseapp.processRecovery({0x1b3b300, 0x279fff0}, 0x27d5a28?)\n\tgithub.com/cosmos/cosmos-sdk@v0.45.16/baseapp/recovery.go:33 +0x5e\ngithub.com/cosmos/cosmos-sdk/baseapp.(*BaseApp).runTx.func1()\n\tgithub.com/cosmos/cosmos-sdk@v0.45.16/baseapp/baseapp.go:632 +0x110\npanic({0x1b3b300, 0x279fff0})\n\truntime/panic.go:884 +0x212\ngithub.com/cosmos/cosmos-sdk/x/distribution/keeper.Keeper.calculateDelegationRewardsBetween({{0x27acd80, 0xc003ba1be0}, {0x7faf64421db0, 0xc0018bb350}, {{0x7faf64421db0, 0xc0018bb350}, 0xc000132e40, {0x27acd80, 0xc003ba1c10}, {0x27acdd0, ...}, ...}, ...}, ...)\n\tgithub.com/cosmos/cosmos-sdk@v0.45.16/x/distribution/keeper/delegation.go:35 +0x29f\ngithub.com/cosmos/cosmos-sdk/x/distribution/keeper.Keeper.CalculateDelegationRewards({{0x27acd80, 0xc003ba1be0}, {0x7faf64421db0, 0xc0018bb350}, {{0x7faf64421db0, 0xc0018bb350}, 0xc000132e40, {0x27acd80, 0xc003ba1c10}, {0x27acdd0, ...}, ...}, ...}, ...)\n\tgithub.com/cosmos/cosmos-sdk@v0.45.16/x/distribution/keeper/delegation.go:135 +0x5d3\ngithub.com/cosmos/cosmos-sdk/x/distribution/keeper.Keeper.withdrawDelegationRewards({{0x27acd80, 0xc003ba1be0}, {0x7faf64421db0, 0xc0018bb350}, {{0x7faf64421db0, 0xc0018bb350}, 0xc000132e40, {0x27acd80, 0xc003ba1c10}, {0x27acdd0, ...}, ...}, ...}, ...)\n\tgithub.com/cosmos/cosmos-sdk@v0.45.16/x/distribution/keeper/delegation.go:147 +0x23b\ngithub.com/cosmos/cosmos-sdk/x/distribution/keeper.Keeper.WithdrawDelegationRewards({{0x27acd80, 0xc003ba1be0}, {0x7faf64421db0, 0xc0018bb350}, {{0x7faf64421db0, 0xc0018bb350}, 0xc000132e40, {0x27acd80, 0xc003ba1c10}, {0x27acdd0, ...}, ...}, ...}, ...)\n\tgithub.com/cosmos/cosmos-sdk@v0.45.16/x/distribution/keeper/keeper.go:96 +0x1ce\ngithub.com/cosmos/cosmos-sdk/x/distribution/keeper.msgServer.WithdrawDelegatorReward({{{0x27acd80, 0xc003ba1be0}, {0x7faf64421db0, 0xc0018bb350}, {{0x7faf64421db0, 0xc0018bb350}, 0xc000132e40, {0x27acd80, 0xc003ba1c10}, {0x27acdd0, ...}, ...}, ...}}, ...)\n\tgithub.com/cosmos/cosmos-sdk@v0.45.16/x/distribution/keeper/msg_server.go:63 +0x250\ngithub.com/cosmos/cosmos-sdk/x/distribution/types._Msg_WithdrawDelegatorReward_Handler.func1({0x27c41d8, 0xc08fb64b40}, {0x1dca880?, 0xc0fe146160})\n\tgithub.com/cosmos/cosmos-sdk@v0.45.16/x/distribution/types/tx.pb.go:619 +0x78\ngithub.com/cosmos/cosmos-sdk/baseapp.(*MsgServiceRouter).RegisterService.func2.1({0x27c41d8, 0xc08fb64b10}, {0x519826?, 0x40cd4b?}, 0x1e36840?, 0xc0f30f39e0)\n\tgithub.com/cosmos/cosmos-sdk@v0.45.16/baseapp/msg_service_router.go:113 +0xdb\ngithub.com/cosmos/cosmos-sdk/x/distribution/types._Msg_WithdrawDelegatorReward_Handler({0x1e3c2c0?, 0xc000d41080}, {0x27c41d8, 0xc08fb64b10}, 0x24d29d0, 0xc0fe146580)\n\tgithub.com/cosmos/cosmos-sdk@v0.45.16/x/distribution/types/tx.pb.go:621 +0x138\ngithub.com/cosmos/cosmos-sdk/baseapp.(*MsgServiceRouter).RegisterService.func2({{0x27c4168, 0xc000056070}, {0x27d5a28, 0xc040deab80}, {{0x0, 0x0}, {0x0, 0x0}, 0x0, {0x0, ...}, ...}, ...}, ...)\n\tgithub.com/cosmos/cosmos-sdk@v0.45.16/baseapp/msg_service_router.go:126 +0x3d0\ngithub.com/cosmos/cosmos-sdk/baseapp.(*BaseApp).runMsgs(_, {{0x27c4168, 0xc000056070}, {0x27d5a28, 0xc040deab80}, {{0x0, 0x0}, {0x0, 0x0}, 0x0, ...}, ...}, ...)\n\tgithub.com/cosmos/cosmos-sdk@v0.45.16/baseapp/baseapp.go:760 +0x5c5\ngithub.com/cosmos/cosmos-sdk/baseapp.(*BaseApp).runTx(0xc003ac8288, 0x2, {0xc0a7eaa300, 0xf6, 0x100})\n\tgithub.com/cosmos/cosmos-sdk@v0.45.16/baseapp/baseapp.go:717 +0xd0c\ngithub.com/cosmos/cosmos-sdk/baseapp.(*BaseApp).Simulate(0x40f647?, {0xc0a7eaa300?, 0x1ca9c40?, 0xc09abebd01?})\n\tgithub.com/cosmos/cosmos-sdk@v0.45.16/baseapp/test_helpers.go:23 +0x2c\ngithub.com/cosmos/cosmos-sdk/x/auth/tx.txServer.Simulate({{{0x0, 0x0, 0x0}, {0x27e6bd0, 0xc0019438c0}, {0x0, 0x0}, {0x27cae80, 0xc0018be920}, {0x27dd2d8, ...}, ...}, ...}, ...)\n\tgithub.com/cosmos/cosmos-sdk@v0.45.16/x/auth/tx/service.go:120 +0x12e\ngithub.com/cosmos/cosmos-sdk/types/tx._Service_Simulate_Handler({0x1d4a0a0?, 0xc003351380}, {0x27c41d8, 0xc07814cc00}, 0xc0c7ce6dc0, 0x0)\n\tgithub.com/cosmos/cosmos-sdk@v0.45.16/types/tx/service.pb.go:910 +0x170\ngithub.com/cosmos/cosmos-sdk/baseapp.(*GRPCQueryRouter).RegisterService.func1({{0x27c4168, 0xc000056070}, {0x27d5a28, 0xc040dcf540}, {{0xb, 0x0}, {0xc0db735f30, 0x8}, 0x6d86bc, {0x2cca9ed4, ...}, ...}, ...}, ...)\n\tgithub.com/cosmos/cosmos-sdk@v0.45.16/baseapp/grpcrouter.go:85 +0x230\ngithub.com/cosmos/cosmos-sdk/baseapp.(*BaseApp).handleQueryGRPC(0xc003ac9488, 0xc00792a210, {{0xc0a7eaa200, 0xf9, 0xf9}, {0x1e87568, 0x23}, 0x6d86bc, 0x0})\n\tgithub.com/cosmos/cosmos-sdk@v0.45.16/baseapp/abci.go:601 +0x1cf\ngithub.com/cosmos/cosmos-sdk/baseapp.(*BaseApp).Query(0xc003ac9488, {{0xc0a7eaa200, 0xf9, 0xf9}, {0x1e87568, 0x23}, 0x6d86bc, 0x0})\n\tgithub.com/cosmos/cosmos-sdk@v0.45.16/baseapp/abci.go:445 +0x6ee\ngithub.com/tendermint/tendermint/abci/client.(*localClient).QuerySync(0xc0094dccc0, {{0xc0a7eaa200, 0xf9, 0xf9}, {0x1e87568, 0x23}, 0x0, 0x0})\n\tgithub.com/tendermint/tendermint@v0.34.27/abci/client/local_client.go:256 +0x171\ngithub.com/tendermint/tendermint/proxy.(*appConnQuery).QuerySync(0x160?, {{0xc0a7eaa200, 0xf9, 0xf9}, {0x1e87568, 0x23}, 0x0, 0x0})\n\tgithub.com/tendermint/tendermint@v0.34.27/proxy/app_conn.go:159 +0x6e\ngithub.com/tendermint/tendermint/rpc/core.ABCIQuery(0x80?, {0x1e87568?, 0x0?}, {0xc0a7eaa200?, 0xc03ece69a0?, 0xc017e5a6d0?}, 0x5ceb9b?, 0xe8?)\n\tgithub.com/tendermint/tendermint@v0.34.27/rpc/core/abci.go:20 +0xa6\ngithub.com/tendermint/tendermint/rpc/client/local.(*Local).ABCIQueryWithOptions(0x40?, {0x0?, 0xc017e5a488?}, {0x1e87568?, 0x0?}, {0xc0a7eaa200?, 0xf07aa2?, 0x0?}, {0x0, 0x0})\n\tgithub.com/tendermint/tendermint@v0.34.27/rpc/client/local/local.go:87 +0x45\ngithub.com/cosmos/cosmos-sdk/client.Context.queryABCI({{0x0, 0x0, 0x0}, {0x27e6bd0, 0xc0019438c0}, {0xc0072b0070, 0x8}, {0x27cae80, 0xc0018be920}, {0x27dd2d8, ...}, ...}, ...)\n\tgithub.com/cosmos/cosmos-sdk@v0.45.16/client/query.go:94 +0x1ab\ngithub.com/cosmos/cosmos-sdk/client.Context.QueryABCI(...)\n\tgithub.com/cosmos/cosmos-sdk@v0.45.16/client/query.go:57\ngithub.com/cosmos/cosmos-sdk/client.Context.Invoke({{0x0, 0x0, 0x0}, {0x27e6bd0, 0xc0019438c0}, {0xc0072b0070, 0x8}, {0x27cae80, 0xc0018be920}, {0x27dd2d8, ...}, ...}, ...)\n\tgithub.com/cosmos/cosmos-sdk@v0.45.16/client/grpc_query.go:81 +0x59d\ngithub.com/cosmos/cosmos-sdk/types/tx.(*serviceClient).Simulate(0xc0001f3aa0, {0x27c41d8, 0xc0dcbc2090}, 0x1bda780?, {0xc0bcf03c20, 0x2, 0x2})\n\tgithub.com/cosmos/cosmos-sdk@v0.45.16/types/tx/service.pb.go:821 +0xce\ngithub.com/cosmos/cosmos-sdk/types/tx.request_Service_Simulate_0({0x27c41d8, 0xc0dcbc2090}, {0x27c82e0, 0xc006fc20f0}, {0x27c77a0, 0xc0001f3aa0}, 0xc03aa93c00, 0x4?)\n\tgithub.com/cosmos/cosmos-sdk@v0.45.16/types/tx/service.pb.gw.go:46 +0x283\ngithub.com/cosmos/cosmos-sdk/types/tx.RegisterServiceHandlerClient.func1({0x27c2280, 0xc0f30f2ba0}, 0xc03aa93c00, 0xc00053cd80?)\n\tgithub.com/cosmos/cosmos-sdk@v0.45.16/types/tx/service.pb.gw.go:420 +0x16e\ngithub.com/grpc-ecosystem/grpc-gateway/runtime.(*ServeMux).ServeHTTP(0xc004edaaf0, {0x27c2280, 0xc0f30f2ba0}, 0xc03aa93c00)\n\tgithub.com/grpc-ecosystem/grpc-gateway@v1.16.0/runtime/mux.go:240 +0xcd6\ngithub.com/gorilla/mux.(*Router).ServeHTTP(0xc00a908000, {0x27c2280, 0xc0f30f2ba0}, 0xc03aa93a00)\n\tgithub.com/gorilla/mux@v1.8.0/mux.go:210 +0x1cf\ngithub.com/tendermint/tendermint/rpc/jsonrpc/server.maxBytesHandler.ServeHTTP({{0x27a61e0?, 0xc00a908000?}, 0x40f647?}, {0x27c2280?, 0xc0f30f2ba0}, 0xc03aa93a00)\n\tgithub.com/tendermint/tendermint@v0.34.27/rpc/jsonrpc/server/http_server.go:256 +0x124\ngithub.com/tendermint/tendermint/rpc/jsonrpc/server.RecoverAndLogHandler.func1({0x27c2910?, 0xc0358f67e0}, 0xc03aa93a00)\n\tgithub.com/tendermint/tendermint@v0.34.27/rpc/jsonrpc/server/http_server.go:229 +0x37f\nnet/http.HandlerFunc.ServeHTTP(0x0?, {0x27c2910?, 0xc0358f67e0?}, 0x959b34?)\n\tnet/http/server.go:2109 +0x2f\nnet/http.serverHandler.ServeHTTP({0x27ae158?}, {0x27c2910, 0xc0358f67e0}, 0xc03aa93a00)\n\tnet/http/server.go:2947 +0x30c\nnet/http.(*conn).serve(0xc09a413b80, {0x27c41d8, 0xc00ab08420})\n\tnet/http/server.go:1991 +0x607\ncreated by net/http.(*Server).Serve\n\tnet/http/server.go:3102 +0x4db\n: panic [cosmos/cosmos-sdk@v0.45.16/baseapp/recovery.go:69] With gas wanted: '0' and gas used: '60461' : unknown request",
    "details": [
    ]
}
```
